name: Site Config Jsonapi
type: module
description: Provides a JSONAPI resource to expose the stored config.
package: Site Config
core_version_requirement: ^10 || ^11
dependencies:
  - site_config:site_config
  - drupal:jsonapi
  - jsonapi_resources:jsonapi_resources
