site_config_jsonapi.config_list:
  path: '/%jsonapi%/site-config'
  defaults:
    _jsonapi_resource: Drupal\site_config_jsonapi\Resource\SiteConfigListResource
  requirements:
    # No access restriction for this public resource.
    _access: 'TRUE'
site_config_jsonapi.config_item:
  path: '/%jsonapi%/site-config/item/{id}'
  defaults:
    _jsonapi_resource: Drupal\site_config_jsonapi\Resource\SiteConfigItemResource
  requirements:
    # No access restriction for this public resource.
    _access: 'TRUE'
