name: Site Config Rest
type: module
description: Provides a Rest resource to expose the stored config.
package: Site Config
core_version_requirement: ^10 || ^11
dependencies:
  - site_config:site_config
  - drupal:rest
